import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { feedbackStyles } from "@langjournal/editor";
import { SidebarProvider } from "@langjournal/ui/components/sidebar";
import { AppSidebar } from "../components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <style dangerouslySetInnerHTML={{ __html: feedbackStyles }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#FDFCF8]`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full h-screen p-4">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
