import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@langjournal/ui/components/sidebar";
import { AppSidebar } from "../components";
import { LLMProvider } from "../components/llm-provider";
import { Lexend, Plus_Jakarta_Sans } from "next/font/google";
import { ViewTransition } from "react";
import { PageTransition } from "@/components/page-transition/page-transition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  weight: ["400", "500", "600", "700"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${lexend.variable} ${plusJakartaSans.variable} ${geistSans.variable} ${geistMono.variable} bg-[#F7F6F2]`}
      >
        <SidebarProvider>
          <LLMProvider />
          <AppSidebar />
          <PageTransition>
            <main className="w-full h-screen">{children}</main>
          </PageTransition>
        </SidebarProvider>
      </body>
    </html>
  );
}
