import type { Metadata } from "next";
import localFont from "next/font/local";
import "@langjournal/ui/globals.css";
import "./globals.css";
import { SidebarProvider } from "@langjournal/ui/components/sidebar";
import { AppSidebar } from "../components";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <SidebarProvider>
                    <AppSidebar />
                    <main>
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
